### ISSUE TITLE
ipynb-py-convert saves to an older nbformat_minor, causing issues with notebooks that use plotly

### ISSUE THREAD

**Issue by pkthong** [kiwi0fruit/ipynb-py-convert#4]
When a .py is converted, and using plotly, the resulting ipynb errors out in jupyter with "Notebook Validation failed: {...} is not valid under any of the given schemas"

Steps for reproduction:
- Create a .py file that outputs an interactive graph via plotly 
- Convert .py to .ipynb using ipynb-py-convert
- Run .ipynb in jupyter
- Try to save notebook with output in jupyter
- Observe error.

**Comment by pkthong** [comment]
Resolution:  Change nbformat_minor to 4 (https://stackoverflow.com/questions/42285255/plotly-plots-in-jupyter-notebooks-validation-fails-when-saving)

**Comment by kiwi0fruit** [comment]
merged https://github.com/kiwi0fruit/ipynb-py-convert/pull/5
